-- TABLE
CREATE TABLE Cliente ("id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,"nome"	TEXT NOT NULL,"idade"	INTEGER NOT NULL,"cpf"	TEXT NOT NULL,"rg"	TEXT NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
